USE [master]
GO

IF NOT EXISTS (SELECT 1 FROM sys.databases WHERE name = 'db_WebApiCliente')
	BEGIN
		CREATE DATABASE db_WebApiCliente
		 CONTAINMENT = NONE
		 ON  PRIMARY 
		( NAME = N'db_WebApiCliente', FILENAME = N'/var/opt/mssql/data/db_WebApiCliente.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
		 LOG ON 
		( NAME = N'db_WebApiCliente_log', FILENAME = N'/var/opt/mssql/data/db_WebApiCliente_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
		

		IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
		begin
			EXEC db_WebApiCliente.[dbo].[sp_fulltext_database] @action = 'enable'
		end
		

		ALTER DATABASE db_WebApiCliente SET ANSI_NULL_DEFAULT OFF 
		

		ALTER DATABASE db_WebApiCliente SET ANSI_NULLS OFF 
		

		ALTER DATABASE db_WebApiCliente SET ANSI_PADDING OFF 
		

		ALTER DATABASE db_WebApiCliente SET ANSI_WARNINGS OFF 
		

		ALTER DATABASE db_WebApiCliente SET ARITHABORT OFF 
		

		ALTER DATABASE db_WebApiCliente SET AUTO_CLOSE OFF 
		

		ALTER DATABASE db_WebApiCliente SET AUTO_SHRINK OFF 
		
		ALTER DATABASE db_WebApiCliente SET AUTO_UPDATE_STATISTICS ON 
		
		ALTER DATABASE db_WebApiCliente SET CURSOR_CLOSE_ON_COMMIT OFF 
		
		ALTER DATABASE db_WebApiCliente SET CURSOR_DEFAULT  GLOBAL 
		
		ALTER DATABASE db_WebApiCliente SET CONCAT_NULL_YIELDS_NULL OFF 
		
		ALTER DATABASE db_WebApiCliente SET NUMERIC_ROUNDABORT OFF 
		
		ALTER DATABASE db_WebApiCliente SET QUOTED_IDENTIFIER OFF 
		
		ALTER DATABASE db_WebApiCliente SET RECURSIVE_TRIGGERS OFF 
		
		ALTER DATABASE db_WebApiCliente SET  DISABLE_BROKER 
		
		ALTER DATABASE db_WebApiCliente SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
		
		ALTER DATABASE db_WebApiCliente SET DATE_CORRELATION_OPTIMIZATION OFF 
		
		ALTER DATABASE db_WebApiCliente SET TRUSTWORTHY OFF 
		
		ALTER DATABASE db_WebApiCliente SET ALLOW_SNAPSHOT_ISOLATION OFF 
		
		ALTER DATABASE db_WebApiCliente SET PARAMETERIZATION SIMPLE 
		
		ALTER DATABASE db_WebApiCliente SET READ_COMMITTED_SNAPSHOT OFF 
		
		ALTER DATABASE db_WebApiCliente SET HONOR_BROKER_PRIORITY OFF 
		
		ALTER DATABASE db_WebApiCliente SET RECOVERY FULL 
		
		ALTER DATABASE db_WebApiCliente SET  MULTI_USER 
		
		ALTER DATABASE db_WebApiCliente SET PAGE_VERIFY CHECKSUM  
		
		ALTER DATABASE db_WebApiCliente SET DB_CHAINING OFF 
		
		ALTER DATABASE db_WebApiCliente SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
		
		ALTER DATABASE db_WebApiCliente SET TARGET_RECOVERY_TIME = 60 SECONDS 
		
		ALTER DATABASE db_WebApiCliente SET DELAYED_DURABILITY = DISABLED 
		
		ALTER DATABASE db_WebApiCliente SET QUERY_STORE = OFF
		
		ALTER DATABASE db_WebApiCliente SET  READ_WRITE 		
	END


USE db_WebApiCliente